package com.manuflowers.recyclerviewdemo.creatures_list.presentation

import com.manuflowers.recyclerviewdemo.creatures_list.data.ExternalCreaturesRepository

class CreaturesListViewModel(private val externalCreaturesRepository: ExternalCreaturesRepository) {
}